// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package server

import (
	"context"

	"douyin/rpc/user/internal/logic"
	"douyin/rpc/user/internal/svc"
	"douyin/rpc/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Ping(ctx context.Context, in *user.Request) (*user.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *UserServer) CreateUser(ctx context.Context, in *user.CreateUserRequest) (*user.CreateUserResponse, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServer) SelectUserByName(ctx context.Context, in *user.SelectUserByNameRequest) (*user.SelectUserByNameResponse, error) {
	l := logic.NewSelectUserByNameLogic(ctx, s.svcCtx)
	return l.SelectUserByName(in)
}

func (s *UserServer) SelectUserByID(ctx context.Context, in *user.SelectUserByIDRequest) (*user.SelectUserByIDResponse, error) {
	l := logic.NewSelectUserByIDLogic(ctx, s.svcCtx)
	return l.SelectUserByID(in)
}

func (s *UserServer) SelectWorkCount(ctx context.Context, in *user.SelectWorkCountRequest) (*user.SelectWorkCountResponse, error) {
	l := logic.NewSelectWorkCountLogic(ctx, s.svcCtx)
	return l.SelectWorkCount(in)
}

func (s *UserServer) SelectUserListByIDs(ctx context.Context, in *user.SelectUserListByIDsRequest) (*user.SelectUserListByIDsResponse, error) {
	l := logic.NewSelectUserListByIDsLogic(ctx, s.svcCtx)
	return l.SelectUserListByIDs(in)
}

func (s *UserServer) FavoriteVideo(ctx context.Context, in *user.FavoriteVideoRequest) (*user.FavoriteVideoResponse, error) {
	l := logic.NewFavoriteVideoLogic(ctx, s.svcCtx)
	return l.FavoriteVideo(in)
}

func (s *UserServer) SelectFavoriteVideoByUserID(ctx context.Context, in *user.SelectFavoriteVideoByUserIDRequest) (*user.SelectFavoriteVideoByUserIDResponse, error) {
	l := logic.NewSelectFavoriteVideoByUserIDLogic(ctx, s.svcCtx)
	return l.SelectFavoriteVideoByUserID(in)
}

func (s *UserServer) UpdateUserInfo(ctx context.Context, in *user.UpdateUserInfoRequest) (*user.UpdateUserInfoResponse, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

func (s *UserServer) SearchUser(ctx context.Context, in *user.SearchUserRequest) (*user.SearchUserResponse, error) {
	l := logic.NewSearchUserLogic(ctx, s.svcCtx)
	return l.SearchUser(in)
}
