// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: contact.proto

package contact_client

import (
	"context"

	"douyin/rpc/contact/contact"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateMessageRequest            = contact.CreateMessageRequest
	CreateMessageResponse           = contact.CreateMessageResponse
	FollowRequest                   = contact.FollowRequest
	FollowResponse                  = contact.FollowResponse
	GetMessageNewestRequest         = contact.GetMessageNewestRequest
	GetMessageNewestResponse        = contact.GetMessageNewestResponse
	IsFollowedRequest               = contact.IsFollowedRequest
	IsFollowedResponse              = contact.IsFollowedResponse
	Message                         = contact.Message
	MessageListRequest              = contact.MessageListRequest
	MessageListResponse             = contact.MessageListResponse
	Request                         = contact.Request
	Response                        = contact.Response
	SelectFollowerByUserIDRequest   = contact.SelectFollowerByUserIDRequest
	SelectFollowerByUserIDResponse  = contact.SelectFollowerByUserIDResponse
	SelectFollowingByUserIDRequest  = contact.SelectFollowingByUserIDRequest
	SelectFollowingByUserIDResponse = contact.SelectFollowingByUserIDResponse

	Contact interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error)
		MessageList(ctx context.Context, in *MessageListRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
		GetMessageNewest(ctx context.Context, in *GetMessageNewestRequest, opts ...grpc.CallOption) (*GetMessageNewestResponse, error)
		Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error)
		SelectFollowingByUserID(ctx context.Context, in *SelectFollowingByUserIDRequest, opts ...grpc.CallOption) (*SelectFollowingByUserIDResponse, error)
		SelectFollowerByUserID(ctx context.Context, in *SelectFollowerByUserIDRequest, opts ...grpc.CallOption) (*SelectFollowerByUserIDResponse, error)
		IsFollowed(ctx context.Context, in *IsFollowedRequest, opts ...grpc.CallOption) (*IsFollowedResponse, error)
	}

	defaultContact struct {
		cli zrpc.Client
	}
)

func NewContact(cli zrpc.Client) Contact {
	return &defaultContact{
		cli: cli,
	}
}

func (m *defaultContact) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := contact.NewContactClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultContact) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error) {
	client := contact.NewContactClient(m.cli.Conn())
	return client.CreateMessage(ctx, in, opts...)
}

func (m *defaultContact) MessageList(ctx context.Context, in *MessageListRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	client := contact.NewContactClient(m.cli.Conn())
	return client.MessageList(ctx, in, opts...)
}

func (m *defaultContact) GetMessageNewest(ctx context.Context, in *GetMessageNewestRequest, opts ...grpc.CallOption) (*GetMessageNewestResponse, error) {
	client := contact.NewContactClient(m.cli.Conn())
	return client.GetMessageNewest(ctx, in, opts...)
}

func (m *defaultContact) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error) {
	client := contact.NewContactClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

func (m *defaultContact) SelectFollowingByUserID(ctx context.Context, in *SelectFollowingByUserIDRequest, opts ...grpc.CallOption) (*SelectFollowingByUserIDResponse, error) {
	client := contact.NewContactClient(m.cli.Conn())
	return client.SelectFollowingByUserID(ctx, in, opts...)
}

func (m *defaultContact) SelectFollowerByUserID(ctx context.Context, in *SelectFollowerByUserIDRequest, opts ...grpc.CallOption) (*SelectFollowerByUserIDResponse, error) {
	client := contact.NewContactClient(m.cli.Conn())
	return client.SelectFollowerByUserID(ctx, in, opts...)
}

func (m *defaultContact) IsFollowed(ctx context.Context, in *IsFollowedRequest, opts ...grpc.CallOption) (*IsFollowedResponse, error) {
	client := contact.NewContactClient(m.cli.Conn())
	return client.IsFollowed(ctx, in, opts...)
}
