// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: video.proto

package server

import (
	"context"

	"douyin/rpc/video/internal/logic"
	"douyin/rpc/video/internal/svc"
	"douyin/rpc/video/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServer) Ping(ctx context.Context, in *video.Request) (*video.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *VideoServer) CreateVideo(ctx context.Context, in *video.CreateVideoRequest) (*video.CreateVideoResponse, error) {
	l := logic.NewCreateVideoLogic(ctx, s.svcCtx)
	return l.CreateVideo(in)
}

func (s *VideoServer) SelectVideosByUserID(ctx context.Context, in *video.SelectVideosByUserIDRequest) (*video.SelectVideosByUserIDResponse, error) {
	l := logic.NewSelectVideosByUserIDLogic(ctx, s.svcCtx)
	return l.SelectVideosByUserID(in)
}

func (s *VideoServer) SelectVideoListByVideoID(ctx context.Context, in *video.SelectVideoListByVideoIDRequest) (*video.SelectVideoListByVideoIDResponse, error) {
	l := logic.NewSelectVideoListByVideoIDLogic(ctx, s.svcCtx)
	return l.SelectVideoListByVideoID(in)
}

func (s *VideoServer) UpdateVideoURL(ctx context.Context, in *video.UpdateVideoURLRequest) (*video.UpdateVideoURLResponse, error) {
	l := logic.NewUpdateVideoURLLogic(ctx, s.svcCtx)
	return l.UpdateVideoURL(in)
}

func (s *VideoServer) SelectFeedVideoList(ctx context.Context, in *video.SelectFeedVideoListRequest) (*video.SelectFeedVideoListResponse, error) {
	l := logic.NewSelectFeedVideoListLogic(ctx, s.svcCtx)
	return l.SelectFeedVideoList(in)
}

func (s *VideoServer) SelectFeedVideoByTopic(ctx context.Context, in *video.SelectFeedVideoByTopicRequest) (*video.SelectFeedVideoByTopicResponse, error) {
	l := logic.NewSelectFeedVideoByTopicLogic(ctx, s.svcCtx)
	return l.SelectFeedVideoByTopic(in)
}

func (s *VideoServer) SearchVideoByKeyword(ctx context.Context, in *video.SearchVideoByKeywordRequest) (*video.SearchVideoByKeywordResponse, error) {
	l := logic.NewSearchVideoByKeywordLogic(ctx, s.svcCtx)
	return l.SearchVideoByKeyword(in)
}

func (s *VideoServer) CommentAdd(ctx context.Context, in *video.CommentAddRequest) (*video.CommentAddResponse, error) {
	l := logic.NewCommentAddLogic(ctx, s.svcCtx)
	return l.CommentAdd(in)
}

func (s *VideoServer) CommentDelete(ctx context.Context, in *video.CommentDeleteRequest) (*video.CommentDeleteResponse, error) {
	l := logic.NewCommentDeleteLogic(ctx, s.svcCtx)
	return l.CommentDelete(in)
}

func (s *VideoServer) GetCommentsByVideoID(ctx context.Context, in *video.GetCommentsByVideoIDRequest) (*video.GetCommentsByVideoIDResponse, error) {
	l := logic.NewGetCommentsByVideoIDLogic(ctx, s.svcCtx)
	return l.GetCommentsByVideoID(in)
}

func (s *VideoServer) GetCommentsByVideoIDFromMaster(ctx context.Context, in *video.GetCommentsByVideoIDFromMasterRequest) (*video.GetCommentsByVideoIDFromMasterResponse, error) {
	l := logic.NewGetCommentsByVideoIDFromMasterLogic(ctx, s.svcCtx)
	return l.GetCommentsByVideoIDFromMaster(in)
}
