// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: contact.proto

package server

import (
	"context"

	"douyin/rpc/contact/contact"
	"douyin/rpc/contact/internal/logic"
	"douyin/rpc/contact/internal/svc"
)

type ContactServer struct {
	svcCtx *svc.ServiceContext
	contact.UnimplementedContactServer
}

func NewContactServer(svcCtx *svc.ServiceContext) *ContactServer {
	return &ContactServer{
		svcCtx: svcCtx,
	}
}

func (s *ContactServer) Ping(ctx context.Context, in *contact.Request) (*contact.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *ContactServer) CreateMessage(ctx context.Context, in *contact.CreateMessageRequest) (*contact.CreateMessageResponse, error) {
	l := logic.NewCreateMessageLogic(ctx, s.svcCtx)
	return l.CreateMessage(in)
}

func (s *ContactServer) MessageList(ctx context.Context, in *contact.MessageListRequest) (*contact.MessageListResponse, error) {
	l := logic.NewMessageListLogic(ctx, s.svcCtx)
	return l.MessageList(in)
}

func (s *ContactServer) GetMessageNewest(ctx context.Context, in *contact.GetMessageNewestRequest) (*contact.GetMessageNewestResponse, error) {
	l := logic.NewGetMessageNewestLogic(ctx, s.svcCtx)
	return l.GetMessageNewest(in)
}

func (s *ContactServer) Follow(ctx context.Context, in *contact.FollowRequest) (*contact.FollowResponse, error) {
	l := logic.NewFollowLogic(ctx, s.svcCtx)
	return l.Follow(in)
}

func (s *ContactServer) SelectFollowingByUserID(ctx context.Context, in *contact.SelectFollowingByUserIDRequest) (*contact.SelectFollowingByUserIDResponse, error) {
	l := logic.NewSelectFollowingByUserIDLogic(ctx, s.svcCtx)
	return l.SelectFollowingByUserID(in)
}

func (s *ContactServer) SelectFollowerByUserID(ctx context.Context, in *contact.SelectFollowerByUserIDRequest) (*contact.SelectFollowerByUserIDResponse, error) {
	l := logic.NewSelectFollowerByUserIDLogic(ctx, s.svcCtx)
	return l.SelectFollowerByUserID(in)
}

func (s *ContactServer) IsFollowed(ctx context.Context, in *contact.IsFollowedRequest) (*contact.IsFollowedResponse, error) {
	l := logic.NewIsFollowedLogic(ctx, s.svcCtx)
	return l.IsFollowed(in)
}
