// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: video.proto

//    goctl rpc protoc video.proto --go_out=. --go-grpc_out=. --zrpc_out=. --style=go_zero

package video

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Video_Ping_FullMethodName                           = "/video.Video/Ping"
	Video_CreateVideo_FullMethodName                    = "/video.Video/CreateVideo"
	Video_SelectVideosByUserID_FullMethodName           = "/video.Video/SelectVideosByUserID"
	Video_SelectVideoListByVideoID_FullMethodName       = "/video.Video/SelectVideoListByVideoID"
	Video_UpdateVideoURL_FullMethodName                 = "/video.Video/UpdateVideoURL"
	Video_SelectFeedVideoList_FullMethodName            = "/video.Video/SelectFeedVideoList"
	Video_SelectFeedVideoByTopic_FullMethodName         = "/video.Video/SelectFeedVideoByTopic"
	Video_SearchVideoByKeyword_FullMethodName           = "/video.Video/SearchVideoByKeyword"
	Video_CommentAdd_FullMethodName                     = "/video.Video/CommentAdd"
	Video_CommentDelete_FullMethodName                  = "/video.Video/CommentDelete"
	Video_GetCommentsByVideoID_FullMethodName           = "/video.Video/GetCommentsByVideoID"
	Video_GetCommentsByVideoIDFromMaster_FullMethodName = "/video.Video/GetCommentsByVideoIDFromMaster"
)

// VideoClient is the client API for Video service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*CreateVideoResponse, error)
	SelectVideosByUserID(ctx context.Context, in *SelectVideosByUserIDRequest, opts ...grpc.CallOption) (*SelectVideosByUserIDResponse, error)
	SelectVideoListByVideoID(ctx context.Context, in *SelectVideoListByVideoIDRequest, opts ...grpc.CallOption) (*SelectVideoListByVideoIDResponse, error)
	UpdateVideoURL(ctx context.Context, in *UpdateVideoURLRequest, opts ...grpc.CallOption) (*UpdateVideoURLResponse, error)
	SelectFeedVideoList(ctx context.Context, in *SelectFeedVideoListRequest, opts ...grpc.CallOption) (*SelectFeedVideoListResponse, error)
	SelectFeedVideoByTopic(ctx context.Context, in *SelectFeedVideoByTopicRequest, opts ...grpc.CallOption) (*SelectFeedVideoByTopicResponse, error)
	SearchVideoByKeyword(ctx context.Context, in *SearchVideoByKeywordRequest, opts ...grpc.CallOption) (*SearchVideoByKeywordResponse, error)
	CommentAdd(ctx context.Context, in *CommentAddRequest, opts ...grpc.CallOption) (*CommentAddResponse, error)
	CommentDelete(ctx context.Context, in *CommentDeleteRequest, opts ...grpc.CallOption) (*CommentDeleteResponse, error)
	GetCommentsByVideoID(ctx context.Context, in *GetCommentsByVideoIDRequest, opts ...grpc.CallOption) (*GetCommentsByVideoIDResponse, error)
	GetCommentsByVideoIDFromMaster(ctx context.Context, in *GetCommentsByVideoIDFromMasterRequest, opts ...grpc.CallOption) (*GetCommentsByVideoIDFromMasterResponse, error)
}

type videoClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoClient(cc grpc.ClientConnInterface) VideoClient {
	return &videoClient{cc}
}

func (c *videoClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Video_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*CreateVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVideoResponse)
	err := c.cc.Invoke(ctx, Video_CreateVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) SelectVideosByUserID(ctx context.Context, in *SelectVideosByUserIDRequest, opts ...grpc.CallOption) (*SelectVideosByUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectVideosByUserIDResponse)
	err := c.cc.Invoke(ctx, Video_SelectVideosByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) SelectVideoListByVideoID(ctx context.Context, in *SelectVideoListByVideoIDRequest, opts ...grpc.CallOption) (*SelectVideoListByVideoIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectVideoListByVideoIDResponse)
	err := c.cc.Invoke(ctx, Video_SelectVideoListByVideoID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) UpdateVideoURL(ctx context.Context, in *UpdateVideoURLRequest, opts ...grpc.CallOption) (*UpdateVideoURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVideoURLResponse)
	err := c.cc.Invoke(ctx, Video_UpdateVideoURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) SelectFeedVideoList(ctx context.Context, in *SelectFeedVideoListRequest, opts ...grpc.CallOption) (*SelectFeedVideoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectFeedVideoListResponse)
	err := c.cc.Invoke(ctx, Video_SelectFeedVideoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) SelectFeedVideoByTopic(ctx context.Context, in *SelectFeedVideoByTopicRequest, opts ...grpc.CallOption) (*SelectFeedVideoByTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectFeedVideoByTopicResponse)
	err := c.cc.Invoke(ctx, Video_SelectFeedVideoByTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) SearchVideoByKeyword(ctx context.Context, in *SearchVideoByKeywordRequest, opts ...grpc.CallOption) (*SearchVideoByKeywordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchVideoByKeywordResponse)
	err := c.cc.Invoke(ctx, Video_SearchVideoByKeyword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) CommentAdd(ctx context.Context, in *CommentAddRequest, opts ...grpc.CallOption) (*CommentAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentAddResponse)
	err := c.cc.Invoke(ctx, Video_CommentAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) CommentDelete(ctx context.Context, in *CommentDeleteRequest, opts ...grpc.CallOption) (*CommentDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentDeleteResponse)
	err := c.cc.Invoke(ctx, Video_CommentDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetCommentsByVideoID(ctx context.Context, in *GetCommentsByVideoIDRequest, opts ...grpc.CallOption) (*GetCommentsByVideoIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommentsByVideoIDResponse)
	err := c.cc.Invoke(ctx, Video_GetCommentsByVideoID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetCommentsByVideoIDFromMaster(ctx context.Context, in *GetCommentsByVideoIDFromMasterRequest, opts ...grpc.CallOption) (*GetCommentsByVideoIDFromMasterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommentsByVideoIDFromMasterResponse)
	err := c.cc.Invoke(ctx, Video_GetCommentsByVideoIDFromMaster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServer is the server API for Video service.
// All implementations must embed UnimplementedVideoServer
// for forward compatibility.
type VideoServer interface {
	Ping(context.Context, *Request) (*Response, error)
	CreateVideo(context.Context, *CreateVideoRequest) (*CreateVideoResponse, error)
	SelectVideosByUserID(context.Context, *SelectVideosByUserIDRequest) (*SelectVideosByUserIDResponse, error)
	SelectVideoListByVideoID(context.Context, *SelectVideoListByVideoIDRequest) (*SelectVideoListByVideoIDResponse, error)
	UpdateVideoURL(context.Context, *UpdateVideoURLRequest) (*UpdateVideoURLResponse, error)
	SelectFeedVideoList(context.Context, *SelectFeedVideoListRequest) (*SelectFeedVideoListResponse, error)
	SelectFeedVideoByTopic(context.Context, *SelectFeedVideoByTopicRequest) (*SelectFeedVideoByTopicResponse, error)
	SearchVideoByKeyword(context.Context, *SearchVideoByKeywordRequest) (*SearchVideoByKeywordResponse, error)
	CommentAdd(context.Context, *CommentAddRequest) (*CommentAddResponse, error)
	CommentDelete(context.Context, *CommentDeleteRequest) (*CommentDeleteResponse, error)
	GetCommentsByVideoID(context.Context, *GetCommentsByVideoIDRequest) (*GetCommentsByVideoIDResponse, error)
	GetCommentsByVideoIDFromMaster(context.Context, *GetCommentsByVideoIDFromMasterRequest) (*GetCommentsByVideoIDFromMasterResponse, error)
	mustEmbedUnimplementedVideoServer()
}

// UnimplementedVideoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoServer struct{}

func (UnimplementedVideoServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedVideoServer) CreateVideo(context.Context, *CreateVideoRequest) (*CreateVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVideo not implemented")
}
func (UnimplementedVideoServer) SelectVideosByUserID(context.Context, *SelectVideosByUserIDRequest) (*SelectVideosByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectVideosByUserID not implemented")
}
func (UnimplementedVideoServer) SelectVideoListByVideoID(context.Context, *SelectVideoListByVideoIDRequest) (*SelectVideoListByVideoIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectVideoListByVideoID not implemented")
}
func (UnimplementedVideoServer) UpdateVideoURL(context.Context, *UpdateVideoURLRequest) (*UpdateVideoURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVideoURL not implemented")
}
func (UnimplementedVideoServer) SelectFeedVideoList(context.Context, *SelectFeedVideoListRequest) (*SelectFeedVideoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectFeedVideoList not implemented")
}
func (UnimplementedVideoServer) SelectFeedVideoByTopic(context.Context, *SelectFeedVideoByTopicRequest) (*SelectFeedVideoByTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectFeedVideoByTopic not implemented")
}
func (UnimplementedVideoServer) SearchVideoByKeyword(context.Context, *SearchVideoByKeywordRequest) (*SearchVideoByKeywordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchVideoByKeyword not implemented")
}
func (UnimplementedVideoServer) CommentAdd(context.Context, *CommentAddRequest) (*CommentAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentAdd not implemented")
}
func (UnimplementedVideoServer) CommentDelete(context.Context, *CommentDeleteRequest) (*CommentDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentDelete not implemented")
}
func (UnimplementedVideoServer) GetCommentsByVideoID(context.Context, *GetCommentsByVideoIDRequest) (*GetCommentsByVideoIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentsByVideoID not implemented")
}
func (UnimplementedVideoServer) GetCommentsByVideoIDFromMaster(context.Context, *GetCommentsByVideoIDFromMasterRequest) (*GetCommentsByVideoIDFromMasterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentsByVideoIDFromMaster not implemented")
}
func (UnimplementedVideoServer) mustEmbedUnimplementedVideoServer() {}
func (UnimplementedVideoServer) testEmbeddedByValue()               {}

// UnsafeVideoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServer will
// result in compilation errors.
type UnsafeVideoServer interface {
	mustEmbedUnimplementedVideoServer()
}

func RegisterVideoServer(s grpc.ServiceRegistrar, srv VideoServer) {
	// If the following call pancis, it indicates UnimplementedVideoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Video_ServiceDesc, srv)
}

func _Video_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_CreateVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).CreateVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_CreateVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).CreateVideo(ctx, req.(*CreateVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_SelectVideosByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectVideosByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).SelectVideosByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_SelectVideosByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).SelectVideosByUserID(ctx, req.(*SelectVideosByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_SelectVideoListByVideoID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectVideoListByVideoIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).SelectVideoListByVideoID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_SelectVideoListByVideoID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).SelectVideoListByVideoID(ctx, req.(*SelectVideoListByVideoIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_UpdateVideoURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVideoURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).UpdateVideoURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_UpdateVideoURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).UpdateVideoURL(ctx, req.(*UpdateVideoURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_SelectFeedVideoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectFeedVideoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).SelectFeedVideoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_SelectFeedVideoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).SelectFeedVideoList(ctx, req.(*SelectFeedVideoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_SelectFeedVideoByTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectFeedVideoByTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).SelectFeedVideoByTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_SelectFeedVideoByTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).SelectFeedVideoByTopic(ctx, req.(*SelectFeedVideoByTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_SearchVideoByKeyword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchVideoByKeywordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).SearchVideoByKeyword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_SearchVideoByKeyword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).SearchVideoByKeyword(ctx, req.(*SearchVideoByKeywordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_CommentAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).CommentAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_CommentAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).CommentAdd(ctx, req.(*CommentAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_CommentDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).CommentDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_CommentDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).CommentDelete(ctx, req.(*CommentDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetCommentsByVideoID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentsByVideoIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetCommentsByVideoID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_GetCommentsByVideoID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetCommentsByVideoID(ctx, req.(*GetCommentsByVideoIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetCommentsByVideoIDFromMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentsByVideoIDFromMasterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetCommentsByVideoIDFromMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_GetCommentsByVideoIDFromMaster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetCommentsByVideoIDFromMaster(ctx, req.(*GetCommentsByVideoIDFromMasterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Video_ServiceDesc is the grpc.ServiceDesc for Video service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Video_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.Video",
	HandlerType: (*VideoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Video_Ping_Handler,
		},
		{
			MethodName: "CreateVideo",
			Handler:    _Video_CreateVideo_Handler,
		},
		{
			MethodName: "SelectVideosByUserID",
			Handler:    _Video_SelectVideosByUserID_Handler,
		},
		{
			MethodName: "SelectVideoListByVideoID",
			Handler:    _Video_SelectVideoListByVideoID_Handler,
		},
		{
			MethodName: "UpdateVideoURL",
			Handler:    _Video_UpdateVideoURL_Handler,
		},
		{
			MethodName: "SelectFeedVideoList",
			Handler:    _Video_SelectFeedVideoList_Handler,
		},
		{
			MethodName: "SelectFeedVideoByTopic",
			Handler:    _Video_SelectFeedVideoByTopic_Handler,
		},
		{
			MethodName: "SearchVideoByKeyword",
			Handler:    _Video_SearchVideoByKeyword_Handler,
		},
		{
			MethodName: "CommentAdd",
			Handler:    _Video_CommentAdd_Handler,
		},
		{
			MethodName: "CommentDelete",
			Handler:    _Video_CommentDelete_Handler,
		},
		{
			MethodName: "GetCommentsByVideoID",
			Handler:    _Video_GetCommentsByVideoID_Handler,
		},
		{
			MethodName: "GetCommentsByVideoIDFromMaster",
			Handler:    _Video_GetCommentsByVideoIDFromMaster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video.proto",
}
