// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: contact.proto

package contact

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Contact_Ping_FullMethodName                    = "/contact.Contact/Ping"
	Contact_CreateMessage_FullMethodName           = "/contact.Contact/CreateMessage"
	Contact_MessageList_FullMethodName             = "/contact.Contact/MessageList"
	Contact_GetMessageNewest_FullMethodName        = "/contact.Contact/GetMessageNewest"
	Contact_Follow_FullMethodName                  = "/contact.Contact/Follow"
	Contact_SelectFollowingByUserID_FullMethodName = "/contact.Contact/SelectFollowingByUserID"
	Contact_SelectFollowerByUserID_FullMethodName  = "/contact.Contact/SelectFollowerByUserID"
	Contact_IsFollowed_FullMethodName              = "/contact.Contact/IsFollowed"
)

// ContactClient is the client API for Contact service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContactClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error)
	MessageList(ctx context.Context, in *MessageListRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
	GetMessageNewest(ctx context.Context, in *GetMessageNewestRequest, opts ...grpc.CallOption) (*GetMessageNewestResponse, error)
	Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error)
	SelectFollowingByUserID(ctx context.Context, in *SelectFollowingByUserIDRequest, opts ...grpc.CallOption) (*SelectFollowingByUserIDResponse, error)
	SelectFollowerByUserID(ctx context.Context, in *SelectFollowerByUserIDRequest, opts ...grpc.CallOption) (*SelectFollowerByUserIDResponse, error)
	IsFollowed(ctx context.Context, in *IsFollowedRequest, opts ...grpc.CallOption) (*IsFollowedResponse, error)
}

type contactClient struct {
	cc grpc.ClientConnInterface
}

func NewContactClient(cc grpc.ClientConnInterface) ContactClient {
	return &contactClient{cc}
}

func (c *contactClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Contact_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMessageResponse)
	err := c.cc.Invoke(ctx, Contact_CreateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactClient) MessageList(ctx context.Context, in *MessageListRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageListResponse)
	err := c.cc.Invoke(ctx, Contact_MessageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactClient) GetMessageNewest(ctx context.Context, in *GetMessageNewestRequest, opts ...grpc.CallOption) (*GetMessageNewestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageNewestResponse)
	err := c.cc.Invoke(ctx, Contact_GetMessageNewest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactClient) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowResponse)
	err := c.cc.Invoke(ctx, Contact_Follow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactClient) SelectFollowingByUserID(ctx context.Context, in *SelectFollowingByUserIDRequest, opts ...grpc.CallOption) (*SelectFollowingByUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectFollowingByUserIDResponse)
	err := c.cc.Invoke(ctx, Contact_SelectFollowingByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactClient) SelectFollowerByUserID(ctx context.Context, in *SelectFollowerByUserIDRequest, opts ...grpc.CallOption) (*SelectFollowerByUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectFollowerByUserIDResponse)
	err := c.cc.Invoke(ctx, Contact_SelectFollowerByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactClient) IsFollowed(ctx context.Context, in *IsFollowedRequest, opts ...grpc.CallOption) (*IsFollowedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsFollowedResponse)
	err := c.cc.Invoke(ctx, Contact_IsFollowed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactServer is the server API for Contact service.
// All implementations must embed UnimplementedContactServer
// for forward compatibility.
type ContactServer interface {
	Ping(context.Context, *Request) (*Response, error)
	CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageResponse, error)
	MessageList(context.Context, *MessageListRequest) (*MessageListResponse, error)
	GetMessageNewest(context.Context, *GetMessageNewestRequest) (*GetMessageNewestResponse, error)
	Follow(context.Context, *FollowRequest) (*FollowResponse, error)
	SelectFollowingByUserID(context.Context, *SelectFollowingByUserIDRequest) (*SelectFollowingByUserIDResponse, error)
	SelectFollowerByUserID(context.Context, *SelectFollowerByUserIDRequest) (*SelectFollowerByUserIDResponse, error)
	IsFollowed(context.Context, *IsFollowedRequest) (*IsFollowedResponse, error)
	mustEmbedUnimplementedContactServer()
}

// UnimplementedContactServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContactServer struct{}

func (UnimplementedContactServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedContactServer) CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}
func (UnimplementedContactServer) MessageList(context.Context, *MessageListRequest) (*MessageListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageList not implemented")
}
func (UnimplementedContactServer) GetMessageNewest(context.Context, *GetMessageNewestRequest) (*GetMessageNewestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageNewest not implemented")
}
func (UnimplementedContactServer) Follow(context.Context, *FollowRequest) (*FollowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedContactServer) SelectFollowingByUserID(context.Context, *SelectFollowingByUserIDRequest) (*SelectFollowingByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectFollowingByUserID not implemented")
}
func (UnimplementedContactServer) SelectFollowerByUserID(context.Context, *SelectFollowerByUserIDRequest) (*SelectFollowerByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectFollowerByUserID not implemented")
}
func (UnimplementedContactServer) IsFollowed(context.Context, *IsFollowedRequest) (*IsFollowedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsFollowed not implemented")
}
func (UnimplementedContactServer) mustEmbedUnimplementedContactServer() {}
func (UnimplementedContactServer) testEmbeddedByValue()                 {}

// UnsafeContactServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContactServer will
// result in compilation errors.
type UnsafeContactServer interface {
	mustEmbedUnimplementedContactServer()
}

func RegisterContactServer(s grpc.ServiceRegistrar, srv ContactServer) {
	// If the following call pancis, it indicates UnimplementedContactServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Contact_ServiceDesc, srv)
}

func _Contact_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contact_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contact_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contact_CreateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contact_MessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).MessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contact_MessageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).MessageList(ctx, req.(*MessageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contact_GetMessageNewest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageNewestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).GetMessageNewest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contact_GetMessageNewest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).GetMessageNewest(ctx, req.(*GetMessageNewestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contact_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contact_Follow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).Follow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contact_SelectFollowingByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectFollowingByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).SelectFollowingByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contact_SelectFollowingByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).SelectFollowingByUserID(ctx, req.(*SelectFollowingByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contact_SelectFollowerByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectFollowerByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).SelectFollowerByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contact_SelectFollowerByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).SelectFollowerByUserID(ctx, req.(*SelectFollowerByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contact_IsFollowed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFollowedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).IsFollowed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Contact_IsFollowed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).IsFollowed(ctx, req.(*IsFollowedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Contact_ServiceDesc is the grpc.ServiceDesc for Contact service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Contact_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contact.Contact",
	HandlerType: (*ContactServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Contact_Ping_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _Contact_CreateMessage_Handler,
		},
		{
			MethodName: "MessageList",
			Handler:    _Contact_MessageList_Handler,
		},
		{
			MethodName: "GetMessageNewest",
			Handler:    _Contact_GetMessageNewest_Handler,
		},
		{
			MethodName: "Follow",
			Handler:    _Contact_Follow_Handler,
		},
		{
			MethodName: "SelectFollowingByUserID",
			Handler:    _Contact_SelectFollowingByUserID_Handler,
		},
		{
			MethodName: "SelectFollowerByUserID",
			Handler:    _Contact_SelectFollowerByUserID_Handler,
		},
		{
			MethodName: "IsFollowed",
			Handler:    _Contact_IsFollowed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contact.proto",
}
