// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: video.proto

package video_client

import (
	"context"

	"douyin/rpc/video/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment                                = video.Comment
	CommentAddRequest                      = video.CommentAddRequest
	CommentAddResponse                     = video.CommentAddResponse
	CommentDeleteRequest                   = video.CommentDeleteRequest
	CommentDeleteResponse                  = video.CommentDeleteResponse
	CreateVideoRequest                     = video.CreateVideoRequest
	CreateVideoResponse                    = video.CreateVideoResponse
	GetCommentsByVideoIDFromMasterRequest  = video.GetCommentsByVideoIDFromMasterRequest
	GetCommentsByVideoIDFromMasterResponse = video.GetCommentsByVideoIDFromMasterResponse
	GetCommentsByVideoIDRequest            = video.GetCommentsByVideoIDRequest
	GetCommentsByVideoIDResponse           = video.GetCommentsByVideoIDResponse
	Request                                = video.Request
	Response                               = video.Response
	SearchVideoByKeywordRequest            = video.SearchVideoByKeywordRequest
	SearchVideoByKeywordResponse           = video.SearchVideoByKeywordResponse
	SelectFeedVideoByTopicRequest          = video.SelectFeedVideoByTopicRequest
	SelectFeedVideoByTopicResponse         = video.SelectFeedVideoByTopicResponse
	SelectFeedVideoListRequest             = video.SelectFeedVideoListRequest
	SelectFeedVideoListResponse            = video.SelectFeedVideoListResponse
	SelectVideoListByVideoIDRequest        = video.SelectVideoListByVideoIDRequest
	SelectVideoListByVideoIDResponse       = video.SelectVideoListByVideoIDResponse
	SelectVideosByUserIDRequest            = video.SelectVideosByUserIDRequest
	SelectVideosByUserIDResponse           = video.SelectVideosByUserIDResponse
	UpdateVideoURLRequest                  = video.UpdateVideoURLRequest
	UpdateVideoURLResponse                 = video.UpdateVideoURLResponse
	UserInfo                               = video.UserInfo
	VideoData                              = video.VideoData
	VideoInfo                              = video.VideoInfo

	Video interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*CreateVideoResponse, error)
		SelectVideosByUserID(ctx context.Context, in *SelectVideosByUserIDRequest, opts ...grpc.CallOption) (*SelectVideosByUserIDResponse, error)
		SelectVideoListByVideoID(ctx context.Context, in *SelectVideoListByVideoIDRequest, opts ...grpc.CallOption) (*SelectVideoListByVideoIDResponse, error)
		UpdateVideoURL(ctx context.Context, in *UpdateVideoURLRequest, opts ...grpc.CallOption) (*UpdateVideoURLResponse, error)
		SelectFeedVideoList(ctx context.Context, in *SelectFeedVideoListRequest, opts ...grpc.CallOption) (*SelectFeedVideoListResponse, error)
		SelectFeedVideoByTopic(ctx context.Context, in *SelectFeedVideoByTopicRequest, opts ...grpc.CallOption) (*SelectFeedVideoByTopicResponse, error)
		SearchVideoByKeyword(ctx context.Context, in *SearchVideoByKeywordRequest, opts ...grpc.CallOption) (*SearchVideoByKeywordResponse, error)
		CommentAdd(ctx context.Context, in *CommentAddRequest, opts ...grpc.CallOption) (*CommentAddResponse, error)
		CommentDelete(ctx context.Context, in *CommentDeleteRequest, opts ...grpc.CallOption) (*CommentDeleteResponse, error)
		GetCommentsByVideoID(ctx context.Context, in *GetCommentsByVideoIDRequest, opts ...grpc.CallOption) (*GetCommentsByVideoIDResponse, error)
		GetCommentsByVideoIDFromMaster(ctx context.Context, in *GetCommentsByVideoIDFromMasterRequest, opts ...grpc.CallOption) (*GetCommentsByVideoIDFromMasterResponse, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

func (m *defaultVideo) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultVideo) CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*CreateVideoResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.CreateVideo(ctx, in, opts...)
}

func (m *defaultVideo) SelectVideosByUserID(ctx context.Context, in *SelectVideosByUserIDRequest, opts ...grpc.CallOption) (*SelectVideosByUserIDResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.SelectVideosByUserID(ctx, in, opts...)
}

func (m *defaultVideo) SelectVideoListByVideoID(ctx context.Context, in *SelectVideoListByVideoIDRequest, opts ...grpc.CallOption) (*SelectVideoListByVideoIDResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.SelectVideoListByVideoID(ctx, in, opts...)
}

func (m *defaultVideo) UpdateVideoURL(ctx context.Context, in *UpdateVideoURLRequest, opts ...grpc.CallOption) (*UpdateVideoURLResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.UpdateVideoURL(ctx, in, opts...)
}

func (m *defaultVideo) SelectFeedVideoList(ctx context.Context, in *SelectFeedVideoListRequest, opts ...grpc.CallOption) (*SelectFeedVideoListResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.SelectFeedVideoList(ctx, in, opts...)
}

func (m *defaultVideo) SelectFeedVideoByTopic(ctx context.Context, in *SelectFeedVideoByTopicRequest, opts ...grpc.CallOption) (*SelectFeedVideoByTopicResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.SelectFeedVideoByTopic(ctx, in, opts...)
}

func (m *defaultVideo) SearchVideoByKeyword(ctx context.Context, in *SearchVideoByKeywordRequest, opts ...grpc.CallOption) (*SearchVideoByKeywordResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.SearchVideoByKeyword(ctx, in, opts...)
}

func (m *defaultVideo) CommentAdd(ctx context.Context, in *CommentAddRequest, opts ...grpc.CallOption) (*CommentAddResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.CommentAdd(ctx, in, opts...)
}

func (m *defaultVideo) CommentDelete(ctx context.Context, in *CommentDeleteRequest, opts ...grpc.CallOption) (*CommentDeleteResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.CommentDelete(ctx, in, opts...)
}

func (m *defaultVideo) GetCommentsByVideoID(ctx context.Context, in *GetCommentsByVideoIDRequest, opts ...grpc.CallOption) (*GetCommentsByVideoIDResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetCommentsByVideoID(ctx, in, opts...)
}

func (m *defaultVideo) GetCommentsByVideoIDFromMaster(ctx context.Context, in *GetCommentsByVideoIDFromMasterRequest, opts ...grpc.CallOption) (*GetCommentsByVideoIDFromMasterResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetCommentsByVideoIDFromMaster(ctx, in, opts...)
}
