// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	contact "tiktok-plus/service/http/internal/handler/contact"
	user "tiktok-plus/service/http/internal/handler/user"
	video "tiktok-plus/service/http/internal/handler/video"
	"tiktok-plus/service/http/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/douyin/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/douyin/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
	)
	

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/douyin/user",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/douyin/relation/action",
					Handler: user.FollowsActionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/relatioin/follow/list",
					Handler: user.FollowListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/relation/follower/list",
					Handler: user.FanListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/douyin/feed",
				Handler: video.FeedHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/douyin/publish/action",
					Handler: video.PublishVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/publish/list",
					Handler: video.PublishVideoListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/favorite/list",
					Handler: video.FavoriteListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/douyin/favorite/action",
					Handler: video.FavoriteActionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/douyin/comment/action",
					Handler: video.CommentActionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/comment/list",
					Handler: video.CommentListHandler(serverCtx),
				},

			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/douyin/relation/friend/list",
					Handler: contact.FriendListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/douyin/message/action",
					Handler: contact.SendMessageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/message/chat",
					Handler: contact.HistoryMessageHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/static/:dir/:file",
				Handler: video.FileHandler(serverCtx),
			},
		},
	)
}
