// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package user_client

import (
	"context"

	"douyin/rpc/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateUserRequest                   = user.CreateUserRequest
	CreateUserResponse                  = user.CreateUserResponse
	FavoriteVideoRequest                = user.FavoriteVideoRequest
	FavoriteVideoResponse               = user.FavoriteVideoResponse
	Request                             = user.Request
	Response                            = user.Response
	SearchUserRequest                   = user.SearchUserRequest
	SearchUserResponse                  = user.SearchUserResponse
	SelectFavoriteVideoByUserIDRequest  = user.SelectFavoriteVideoByUserIDRequest
	SelectFavoriteVideoByUserIDResponse = user.SelectFavoriteVideoByUserIDResponse
	SelectUserByIDRequest               = user.SelectUserByIDRequest
	SelectUserByIDResponse              = user.SelectUserByIDResponse
	SelectUserByNameRequest             = user.SelectUserByNameRequest
	SelectUserByNameResponse            = user.SelectUserByNameResponse
	SelectUserListByIDsRequest          = user.SelectUserListByIDsRequest
	SelectUserListByIDsResponse         = user.SelectUserListByIDsResponse
	SelectWorkCountRequest              = user.SelectWorkCountRequest
	SelectWorkCountResponse             = user.SelectWorkCountResponse
	UpdateUserInfoRequest               = user.UpdateUserInfoRequest
	UpdateUserInfoResponse              = user.UpdateUserInfoResponse
	UserInfo                            = user.UserInfo

	User interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
		SelectUserByName(ctx context.Context, in *SelectUserByNameRequest, opts ...grpc.CallOption) (*SelectUserByNameResponse, error)
		SelectUserByID(ctx context.Context, in *SelectUserByIDRequest, opts ...grpc.CallOption) (*SelectUserByIDResponse, error)
		SelectWorkCount(ctx context.Context, in *SelectWorkCountRequest, opts ...grpc.CallOption) (*SelectWorkCountResponse, error)
		SelectUserListByIDs(ctx context.Context, in *SelectUserListByIDsRequest, opts ...grpc.CallOption) (*SelectUserListByIDsResponse, error)
		FavoriteVideo(ctx context.Context, in *FavoriteVideoRequest, opts ...grpc.CallOption) (*FavoriteVideoResponse, error)
		SelectFavoriteVideoByUserID(ctx context.Context, in *SelectFavoriteVideoByUserIDRequest, opts ...grpc.CallOption) (*SelectFavoriteVideoByUserIDResponse, error)
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error)
		SearchUser(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultUser) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUser) SelectUserByName(ctx context.Context, in *SelectUserByNameRequest, opts ...grpc.CallOption) (*SelectUserByNameResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SelectUserByName(ctx, in, opts...)
}

func (m *defaultUser) SelectUserByID(ctx context.Context, in *SelectUserByIDRequest, opts ...grpc.CallOption) (*SelectUserByIDResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SelectUserByID(ctx, in, opts...)
}

func (m *defaultUser) SelectWorkCount(ctx context.Context, in *SelectWorkCountRequest, opts ...grpc.CallOption) (*SelectWorkCountResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SelectWorkCount(ctx, in, opts...)
}

func (m *defaultUser) SelectUserListByIDs(ctx context.Context, in *SelectUserListByIDsRequest, opts ...grpc.CallOption) (*SelectUserListByIDsResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SelectUserListByIDs(ctx, in, opts...)
}

func (m *defaultUser) FavoriteVideo(ctx context.Context, in *FavoriteVideoRequest, opts ...grpc.CallOption) (*FavoriteVideoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.FavoriteVideo(ctx, in, opts...)
}

func (m *defaultUser) SelectFavoriteVideoByUserID(ctx context.Context, in *SelectFavoriteVideoByUserIDRequest, opts ...grpc.CallOption) (*SelectFavoriteVideoByUserIDResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SelectFavoriteVideoByUserID(ctx, in, opts...)
}

func (m *defaultUser) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultUser) SearchUser(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SearchUser(ctx, in, opts...)
}
